# This file defines two functions, makeCacheMatrix() and cacheSolve(), to enable caching of a matrix inverse.
# This way, it's not necessary to calculate the inverse every time it's needed

# Description
#   Return a cacheable matrix. A cacheable matrix is a list containing the following functions:
#     set(x): sets the original matrix
#     get(x): returns the original matrix
#     setInverse(inverse): sets the inverse of the original matrix
#     getInverse(inverse): returns the inverse matrix
#
# Usage
#   makeCacheMatrix(x)
#
# Arguments
#   x: a numeric matrix
makeCacheMatrix <- function(x = matrix()) {
  
    # Initialize the inverse
    inv <- NULL
  
    # Set the original matrix
    set <- function(y) {
      x <<- y
      inv <<- NULL
    }
  
    # Get the original matrix
    get <- function() x
  
    # Set the inverse matrix
    setInverse <- function(inverse) inv <<- inverse
  
    # Get the inverse matrix
    getInverse <- function() inv
  
    # Returns the cacheable matrix container
    list(
        set = set,
        get = get,
        setInverse = setInverse,
        getInverse = getInverse
    )
}

# Description
#   Find the inverse matrix of a cacheable matrix. Calculates the inverse if not calculated yet and saves it in the matrix.
#   Otherwise, returns the inverse contained in the cacheable matrix.
#   This function assumes that the cacheable matrix is invertible.
#
# Usage
#   cacheSolve(x, ...)
#
# Arguments
#   x: cacheable matrix generated by the function makeCacheMatrix()
#   ... : valid optional arguments for solve()
cacheSolve <- function(x, ...) {
    # Try to load the inverse matrix
    inv <- x$getInverse()
    
    # If the inverse is cached, use it instead of calculating the inverse again
    if(!is.null(inv)) {
        message("Getting cached data")
        return(inv)
    }
    
    # Load the value of the original matrix
    data <- x$get()
    
    # Calculates the inverse
    #     Argument 1 is the original matrix
    #     Argument 2 is an identity matrix with the same dimensions as the original matrix
    #     Argument 3 is a set of optional arguments
    inv <- solve(data, diag(dim(data)[1]), ...)
    
    # Set the calculated inverse
    x$setInverse(inv)
    
    # Return the inverse
    inv
}
